export const RENDER_LIGHT_CAMERA_ACTIONS = [
  'create_primitive',
  'set_camera_look_at',
  'set_camera_property',
  'create_camera',
  'set_material_property',
  'assign_builtin_material',
  'set_material_define',
  'assign_project_material',
  'clone_material',
  'swap_technique',
  'sprite_grayscale',
  'camera_screenshot',
  'create_light',
  'set_light_property',
  'set_scene_environment',
] as const;
