export const TRANSFORM_ACTIONS = [
  'create_node',
  'destroy_node',
  'reparent',
  'duplicate_node',
  'set_position',
  'set_rotation',
  'set_scale',
  'set_world_position',
  'set_world_rotation',
  'set_world_scale',
  'set_name',
  'set_active',
  'move_node_up',
  'move_node_down',
  'set_sibling_index',
  'clear_children',
  'reset_transform',
  'group_nodes',
  'batch',
] as const;
