use hmac::{Hmac, Mac};
use serde_json::Value;
use sha2::Sha256;
use std::time::{SystemTime, UNIX_EPOCH};

type HmacSha256 = Hmac<Sha256>;

/// HMAC key embedded at compile time.
/// Generated by `tools/generate-license.mjs --init-keys` and stored in `keys/hmac.key`.
/// This key is used for both generating and verifying License Keys.
/// Security relies on the Rust binary being non-decompilable (strip + LTO).
/// This file must NEVER appear in any repository or distribution package.
const VERIFY_KEY: &[u8; 32] = include_bytes!("../../keys/hmac.key");

const BASE32_ALPHABET: &[u8] = b"ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

const EDITION_PRO: u8 = 0x01;
const EDITION_ENT: u8 = 0x02;

fn base32_decode(input: &str) -> Option<Vec<u8>> {
    let mut lookup = [255u8; 128];
    for (i, &ch) in BASE32_ALPHABET.iter().enumerate() {
        lookup[ch as usize] = i as u8;
        if ch.is_ascii_uppercase() {
            lookup[ch.to_ascii_lowercase() as usize] = i as u8;
        }
    }

    let mut bits: u32 = 0;
    let mut value: u32 = 0;
    let mut result = Vec::new();

    for &ch in input.as_bytes() {
        let idx = if (ch as usize) < 128 {
            lookup[ch as usize]
        } else {
            255
        };
        if idx == 255 {
            continue;
        }
        value = (value << 5) | idx as u32;
        bits += 5;
        if bits >= 8 {
            bits -= 8;
            result.push(((value >> bits) & 0xff) as u8);
        }
    }

    Some(result)
}

fn now_epoch() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

fn edition_name(byte: u8) -> &'static str {
    match byte {
        EDITION_PRO => "pro",
        EDITION_ENT => "enterprise",
        _ => "unknown",
    }
}

fn mask_email_hash(hash_bytes: &[u8]) -> String {
    let hex = hash_bytes
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();
    format!("{}...{}", &hex[..2], &hex[hex.len() - 2..])
}

/// Validate a license key and return edition info.
///
/// Key format: `COCOS-{PRO|ENT}-{seg1}-{seg2}-{seg3}`
/// Payload:    email_hash(4B) + edition(1B) + expiry(4B) + hmac_sig(6B) = 15B
/// Encoding:   Base32 (custom alphabet, no I/O/0/1) → 24 chars → 3×8
pub fn validate(key: &str) -> Value {
    if key.is_empty() {
        return serde_json::json!({
            "valid": false,
            "error": "No license key provided",
            "edition": "community"
        });
    }

    let parts: Vec<&str> = key.split('-').collect();
    if parts.len() != 5 || parts[0] != "COCOS" {
        return serde_json::json!({
            "valid": false,
            "error": "Invalid license key format",
            "edition": "community"
        });
    }

    let edition_header = parts[1];
    let expected_edition_byte = match edition_header {
        "PRO" => EDITION_PRO,
        "ENT" => EDITION_ENT,
        _ => {
            return serde_json::json!({
                "valid": false,
                "error": "Unknown edition in license key",
                "edition": "community"
            });
        }
    };

    let encoded = format!("{}{}{}", parts[2], parts[3], parts[4]);
    let decoded = match base32_decode(&encoded) {
        Some(d) if d.len() >= 15 => d,
        _ => {
            return serde_json::json!({
                "valid": false,
                "error": "License key decode failed",
                "edition": "community"
            });
        }
    };

    let payload = &decoded[..9];
    let sig = &decoded[9..15];

    let mut mac =
        HmacSha256::new_from_slice(VERIFY_KEY).expect("HMAC accepts any key length");
    mac.update(payload);
    let expected_hmac = mac.finalize().into_bytes();
    let expected_sig = &expected_hmac[..6];

    if sig != expected_sig {
        return serde_json::json!({
            "valid": false,
            "error": "License key signature verification failed",
            "edition": "community"
        });
    }

    let edition_byte = payload[4];
    if edition_byte != expected_edition_byte {
        return serde_json::json!({
            "valid": false,
            "error": "Edition mismatch in license key",
            "edition": "community"
        });
    }

    let expiry_ts = u32::from_be_bytes([payload[5], payload[6], payload[7], payload[8]]) as u64;
    let now = now_epoch();

    if now > expiry_ts {
        let expiry_date = format_epoch(expiry_ts);
        return serde_json::json!({
            "valid": false,
            "error": format!("License expired on {}", expiry_date),
            "edition": "community",
            "expiry": expiry_date
        });
    }

    let edition = edition_name(edition_byte);
    let expiry_date = format_epoch(expiry_ts);
    let email_hint = mask_email_hash(&payload[..4]);

    serde_json::json!({
        "valid": true,
        "edition": edition,
        "features": get_edition_features(edition),
        "expiry": expiry_date,
        "licensedTo": email_hint
    })
}

fn format_epoch(ts: u64) -> String {
    let days_since_epoch = ts / 86400;
    let mut y = 1970i64;
    let mut remaining = days_since_epoch as i64;

    loop {
        let days_in_year = if is_leap(y) { 366 } else { 365 };
        if remaining < days_in_year {
            break;
        }
        remaining -= days_in_year;
        y += 1;
    }

    let month_days = if is_leap(y) {
        [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    } else {
        [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    };

    let mut m = 0usize;
    for (i, &md) in month_days.iter().enumerate() {
        if remaining < md as i64 {
            m = i;
            break;
        }
        remaining -= md as i64;
    }

    format!("{:04}-{:02}-{:02}", y, m + 1, remaining + 1)
}

fn is_leap(y: i64) -> bool {
    (y % 4 == 0 && y % 100 != 0) || y % 400 == 0
}

fn get_edition_features(edition: &str) -> Vec<&str> {
    match edition {
        "pro" => vec![
            "engine_action",
            "execute_script",
            "register_custom_macro",
            "animation_tool",
            "physics_tool",
            "reference_image",
            "create_prefab_atomic",
            "import_and_apply_texture",
            "setup_ui_layout",
            "create_tween_animation_atomic",
            "auto_fit_physics_collider",
            "full_scene_operation",
            "full_asset_operation",
            "full_editor_action",
            "scene_generator",
            "batch_engine",
            "scene_audit",
        ],
        "enterprise" => vec![
            "engine_action",
            "execute_script",
            "register_custom_macro",
            "animation_tool",
            "physics_tool",
            "reference_image",
            "create_prefab_atomic",
            "import_and_apply_texture",
            "setup_ui_layout",
            "create_tween_animation_atomic",
            "auto_fit_physics_collider",
            "full_scene_operation",
            "full_asset_operation",
            "full_editor_action",
            "scene_generator",
            "batch_engine",
            "scene_audit",
            "project_linter",
            "operation_log",
            "generative_engine",
        ],
        _ => vec![],
    }
}
